### ISSUE TITLE
The blue color used makes reading the text difficult

### ISSUE THREAD

**Issue by juanjqo** [dqrobotics/dqrobotics.github.io#2]
Hi @bvadorno @mmmarinho 

I realized that is hard to read the instructions for Ubuntu/Python in the [website](https://dqrobotics.github.io/) due to the hue of the blue color used.
I checked it on three different screens (Hp Envy 15, Philips 227E6E and iMac 21.5 late 2009).

In the following lines, the text '-m' and '--upgrade' is very difficult to read.  (Maybe the green color can be used instead)
> python3 -m pip install dqrobotics
> python3 -m pip install dqrobotics --upgrade

Best regards,

Juancho

**Comment by bvadorno** [comment]
Hi, Juancho. 

I agree. Since those colors are assigned automatically according to a global template, we'll try to look at how to change them globally. This, for the moment, has a low priority, though.

Cheers,
Bruno

**Comment by bvadorno** [comment]
I've chosen a lighter color. Could you please verify if it's ok now?

Cheers,
Bruno

**Comment by juanjqo** [comment]
@bvadorno, the new color fixes the problem. 
Now it is ok.
